### ISSUE TITLE
error after kjkompile.sh

### ISSUE THREAD

**Issue by 20harshita** [kframework/k-legacy#2125] opened 2016-01-20 08:32 UTC
harshita@harshita-VPCEH25EN:~/java-semantics/src$ kjkompile.sh

Preprocessing semantics:
[Error] Internal: Uncaught exception thrown of type AssertionError.
Please rerun your program with the --debug flag to generate a stack trace, and
file a bug report at https://github.com/kframework/k/issues

Execution semantics:
Java HotSpot(TM) 64-Bit Server VM warning: INFO: os::commit_memory(0x00000000d8200000, 302514176, 0) failed; error='Cannot allocate memory' (errno=12)
# 
# There is insufficient memory for the Java Runtime Environment to continue.
# Native memory allocation (mmap) failed to map 302514176 bytes for committing reserved memory.
# An error report file with more information is saved as:
# /home/harshita/java-semantics/src/hs_err_pid6100.log

Done
what should i do??

**Comment by daejunpark** [comment] 2016-01-20 12:58
You seem to have no sufficient physical memory or not to have a correct JVM memory setting. @laurayuwen Can you help?

BTW, this seems not an issue of K, but more of Java semantics. @20harshita I recommend you to report further issues into Java semantics repository: https://github.com/kframework/java-semantics/issues which will help us to track of such issues.

Thanks!

**Comment by laurayuwen** [comment] 2016-01-20 19:44
@20harshita I created a copy of this issue in Java-Semantics repository, but unfortunately, I have never seen and nor can I reproduce this problem. I can do no better than google this problem, and this seems to be a general issue not relating to K or Java Semantics, some people say this means that you're running so many programs on your PC that there is no memory left to run this one and no Java option is going to change this. You might consider give your machine one more try or try another machine. Thanks!

**Comment by laurayuwen** [comment] 2016-01-20 19:45
I am closing this issue, if you have further message, please go to https://github.com/kframework/java-semantics/issues/57

**Closed as completed by laurayuwen** 2016-01-20 19:45 UTC
