### ISSUE TITLE
poor error message

### ISSUE THREAD

**Issue by grosu** [kframework/k-legacy#619] opened 2014-06-17 11:57 UTC
I see this message over and over again when I forget to write .Map instead of .:

```
fslwork$ kompile fun-untyped.k
[Error] Critical: unexpected left-hand side data structure format; expected
elements and at most one variable
'_Map_(.K,, GeneratedFreshVar1618:Map )
    File:
/home/grosu/github.grosu/k/tutorial/2_languages/3_fun/1_untyped/2_substitution/fun-untyped.k
    Location: (215,3,215,75)
    Compilation Phase: Compile collections to internal K representation
```

First, I think the main error message has some grammatical error: "expected elements and at most one variable"?  Then line `'_Map_(.K,, GeneratedFreshVar1618:Map )` does not help much.  Since our users will see this message tons of times once they we switch to the new branch, we must do our best to improve it.

**Comment by dwightguth** [comment] 2015-04-27 18:06
duplicate of #373

**Closed as completed by dwightguth** 2015-04-27 18:06 UTC
