### ISSUE TITLE
Can't Install K

### ISSUE THREAD

**Issue by lucaspena** [kframework/k-legacy#1489] opened 2015-05-06 16:27 UTC
When running both "mvn install" and "mvn verify", the installation process hangs after "main:". There were also some errors when installing, such as "java.io.IOException: Cannot run program "kast" (in directory ...)" but this did not stop the installation process.

**Comment by radumereuta** [comment] 2015-05-06 17:11
Could you provide a few more information please?
OS, Java version, make sure you have a recent maven version.

If these things don't work, I could also have a look directly at your computer. It's working fine for most of us, so such problems are interesting.

**Comment by dwightguth** [comment] 2015-05-06 17:13
@radumereuta from the error he mentions I suspect that K is not in his PATH. You might test mvn verify that way and see if it reproduces the issue.

**Comment by radumereuta** [comment] 2015-05-06 17:19
Hmm... true. Also, running the examples could fail if you run the tests on windows. The tests are set up to call `kast`, but on windows you have to call `kast.bat`. It's just some weird thing in how java executes commands.

**Comment by lucaspena** [comment] 2015-05-06 17:21
It seems as though @dwightguth was right, I just added K to my PATH. I'm running mvn verify now to make sure but it looks like it's already gotten farther than it had before. Thanks for your help.

**Comment by traiansf** [comment] 2015-05-06 17:23
For my part, I never run more than mvn package in general, and on  Windows in special.

If K is added to the path, then mvn package seems enough for most practical purposes (unless one wants to stress their own computer by running the mighty K test suite).

**Comment by radumereuta** [comment] 2015-05-06 17:24
I usually run `mvn package -DskipTests`. Even faster. It just builds the tool in order for me to run definitions, skipping all unit tests.

**Comment by grosu** [comment] 2015-05-06 18:28
Guys, can we do something to avoid such silly errors?  I know you will say that this is not urgent and that we have something else which is more important or more intellectually interesting to do, but in the end these minor things matter a lot.  @lucaspena was really motivated, so he bothered to report the issue and try to make it work, but others will simply give up and never look back.  They would rightfully say that if they have problems installing the thing, likely they will also have lots of problems running it, so why bother.  So _please_, let us stop for awhile from what we do and try to find a clean solution to this (which hopefully does not involve asking users to read in detail some README in order to do something that is typically not done when installing a Java app from sources).

**Comment by andreistefanescu** [comment] 2015-05-06 21:03
I think that `ktest` and `mvn package | verify | ...` should not use `PATH` for any of the K related binaries/libraries. @dwightguth is that hard to achieve?

**Comment by dwightguth** [comment] 2015-05-06 21:17
The problem is that we currently use external parsers in order to invoke kast from krun. as a result of this, the command that gets invoked in krun is hard-coded in config.xml files. so that would be kind of tricky. But what we can do is make ktest add the bin directory to the path of every process it spawns.

**Comment by radumereuta** [comment] 2015-05-07 17:49
Fixed in #1494.

**Comment by dwightguth** [comment] 2015-05-07 17:59
@lucaspena please reopen if this does not fix your issue.

**Closed as completed** 2015-05-07 17:58 UTC
