### ISSUE TITLE
basic support for debugging semantics in the Java backend

### ISSUE THREAD

**Issue by yilongli** [kframework/k-legacy#756] opened 2014-07-25 18:47 UTC
Although we don't have a full-fledged semantics debugger yet, we should at least try to add support for basic semantics debugging asap. For example, a user should be able to immediately find whether a rule matches or not, and if not why not and if it does what is the substitution.

**Comment by dwightguth** [comment] 2015-04-27 21:26
Closing duplicate of #1441

**Closed as completed by dwightguth** 2015-04-27 21:26 UTC
Labels: enhancement
