### ISSUE TITLE
KDoc for KORE

### ISSUE THREAD

**Issue by dwightguth** [kframework/k-legacy#1672] opened 2015-08-31 15:19 UTC
Need a version of KDoc that works with KORE (ie latex, html)

**Comment by grosu** [comment] 2015-09-04 13:09
@edgar-pek , please let us know if you encountered or think will encounter any problems with this.

**Comment by grosu** [comment] 2015-09-14 17:03
@edgar-pek ping on kdoc

**Comment by edgar-pek** [comment] 2015-09-14 17:12
@grosu I am sorry I haven't worked on kdoc because I was working on run
time checker for UPenn and OpenFlight.
When do you need me to get it done?

**Comment by grosu** [comment] 2015-09-14 17:24
The point is that we cannot transit to KORE as default and remove the KIL complexity before we have everything work.  We need it by the time all other milestone tasks at https://github.com/kframework/k/milestones/Update%20Tutorial%20for%20KORE are also done, so it will not slow us.  If you have other things on your plate, then we can assign this to somebody else, no problem, but we need to know.

**Comment by edgar-pek** [comment] 2015-09-14 17:30
@grosu ok, I understand, I'll give you ETA by the end of the day.
@dwightguth https://github.com/dwightguth How long do you predict it
might take for KORE n00b to finish this?

**Comment by edgar-pek** [comment] 2015-09-18 14:42
There were roughly three sub-tasks for the project:
- [x] add a --kore flag to kdoc and wire it up to the frontend
- [x] add support in kompile to retrieve the parsed but unflattened concrete syntax of the definition
- [ ] reimplement LatexBackend, PdfBackend, and HtmlBackend as visitors over the concrete syntax
  - [x] create skeletons for all the backends
  - [ ] use experimental bubble parsing?????????????????
  - [ ] create latex backend visitor
  - [ ] create html backend visitor
- [ ] tests 
- [ ] code review

ETA: ~~Monday~~ ~~Tuesday~~ ~~Wednesday~~ Thursday (apologies for the delay)
Delay caused by refactoring of the kompile concrete syntax data structures

**Comment by edgar-pek** [comment] 2015-09-22 04:56
Updated status:
- [x]  add a --kore flag to kdoc and wire it up to the frontend
- [x] add support in kompile to retrieve the parsed but unflattened concrete syntax of the definition
- [ ] reimplement LatexBackend, PdfBackend, and HtmlBackend as visitors over the concrete syntax
Updated ETA: Tuesday (apologies for the delay)

**Comment by grosu** [comment] 2015-10-11 18:03
I would like to clarify something that we discussed in the K meeting, just to make sure we are synchronized with this and have no surprises later on.  @radumereuta , please especially you, let us know if you see any problem with this (and maybe tell us also how comes it is not already done this way?).

The output of the frontend kompiling a full K definition should be a KAST term, namely the meta-level representation of the parsed K definition using the syntax in ekore.k.  That should remove no brackets, no cases for productions, etc.  It should basically be identical to the original full K definition, with nothing lost except, perhaps, white spacing.

Why a meta-level representation instead of a core one?  Well, because we may not want to implement Java data-structures corresponding to EKORE yet.

So what needs to be done here is to split the current frontend in two parts: 1) the actual parser which should take the parser tree into a KAST term (the EKORE meta-representation); and 2) the existing transformations modified to actually transform that meta-EKORE term into a meta-KORE; then we down that resulting meta-KORE and obtain the same KORE definition as now.

Guys, we should have had all this months ago.  Instead, we still have the dirty KIL in the frontend.  Any work that we do in the frontend which is not in the direction above is just a waste and will be thrown away eventually.

**Comment by grosu** [comment] 2015-10-11 18:23
Then, the Latex/PDF/HTML backends should be nothing but straightforward visitors of the initial meta-EKORE.  That is, they would be clients of the very first level in the kompilation pipeline.

**Closed as completed** 2019-09-04 17:32 UTC
Labels: enhancement
