### ISSUE TITLE
bad error message in basic parser

### ISSUE THREAD

**Issue by grosu** [kframework/k-legacy#324] opened 2014-03-29 12:51 UTC
Put this in a file `try.k`:

```
module TRY
  syntax Sort ::= "rule" | "a"
  rule rule => a
endmodule
```

The type `kompile try.k`.  You get this error message, which is poorly formatted and unhelpful:

```
fslwork$ kompile try.k
[Error] Parser: org.kframework.parser.basic.ParseException: Encountered "
"rule" "rule "" at line 3, column 8.
Was expecting:
    <BUBBLE> ...

    File: /home/grosu/try/try.k
```

Please propose a better error message and then implement it.

**Comment by dwightguth** [comment] 2015-04-27 21:20
Closed duplicate of #45

**Closed as completed by dwightguth** 2015-04-27 21:20 UTC
Labels: enhancement
