### ISSUE TITLE
unparsing issue with bracket

### ISSUE THREAD

**Issue by daejunpark** [kframework/k-legacy#1932] opened 2015-12-19 08:05 UTC
Adding a bracket for Int sort (f3ba3bd94563d49112a0d4d9ef11b8ab5f26560e) affects unparsing lambda term (8a24fe8143a921108f0b67930d5c97bf3902ce9f).

**Comment by daejunpark** [comment] 2015-12-19 08:06
@dwightguth do you have an idea why it happened?

**Comment by radumereuta** [comment] 2015-12-19 10:38
Guys. Stop adding brackets for every sort. Only one is needed for K.

**Comment by grosu** [comment] 2015-12-19 15:19
And why is that, @radumereuta?  These domains should have brackets anyway, regardless of K.  If somebody wants to import INT in the syntax of their language, they would expect to have parentheses there when parsing programs, too, not only in the semantics.  I understand your concern, ambiguities, but we have to deal with those ambiguities anyway.  Remember that we now have the module qualification @ notation, too, which can be used when _real_ ambiguities are formed.  By _real_ ambiguity I mean one where the resulting KASTs are distinct.  For example, if one defines parentheses as brackets in their language, then that creates no ambiguities with the K parentheses, as those have the same "semantics" of brackets.  But if one has parentheses as function application in one's language, like in Scheme/LISP, then one as to disambiguate, say, the term `(f)`: in Scheme that means invoking the no-argument function `f`, while in K that means just `f`.

**Comment by laurayuwen** [comment] 2015-12-19 15:38
I don't understand why we need to add brackets to every sort? I see PR#1930 add bracket for Int, Set and Bag in order to use brackets instead of backticks in kool semantics, but it doesn't seem to be the right way. We didn't have backticks for very sort, and yet can use it everywhere.

**Comment by grosu** [comment] 2015-12-19 15:44
I just explained it above.  I can repeat:

These domains should have brackets anyway, regardless of K. If somebody wants to import INT in the syntax of their language, they would expect to have parentheses there when parsing programs, too, not only in the semantics...

**Comment by laurayuwen** [comment] 2015-12-19 16:17
They are two separate concerns, one is If somebody wants to import INT in the syntax of their language, they would expect to have parentheses there when parsing programs, too, not only in the semantics?  This one I am not sure, somebody many and somebody may not. 
The other one is we want to replace where we used backticks with parenthesis. And it doesn't convince me that it needs to be done separately for every sort.

**Comment by cos** [comment] 2015-12-19 16:29
It may be good, instead of adding brackets to every sort, to simply make a module:

```
module BRACKETS
  syntax HAS_BRACKETS ::= "(" HAS_BRACKETS ")" [bracket]
endmodule
```

Then we can subsort `HAS_BRACKETS` to any sort that needs them.

**Comment by grosu** [comment] 2015-12-19 16:35
I think you are misunderstanding the issue, @laurayuwen .  Nobody said that we should add brackets for _every_ sort, except for @radumereuta above, exaggerating.  We should add brackets to all the mathematical domains that ought to have brackets.  And that will also make it unnecessary, to a large extent, to even use the K bracket, so it will likely eliminate the need for backticks, even if we don't rename them to parentheses (but I think we should rename them, too).

Most mathematical domains have parentheses and that has nothing to do with K.  You may want to write programs with symbolic inputs, write symbolic assertions in them, etc., and then just parse the programs without any additional syntax of K.  To do that, you need the entire syntax of the mathematical domain to be defined as part of the mathematical domain.  It is not a matter of whether you want or not to have brackets there, you just have them, the same way you just write parentheses when you do proofs by hand on paper.

My answer to @radumereuta is that we should _not_ stop adding brackets to domains they ought to have brackets only because those might create more ambiguities with the K brackets.

**Comment by grosu** [comment] 2015-12-19 16:50
@cos, I think that would be very risky, because it would then collapse all the syntactic categories with brackets into one.  In Maude or rewriting logic terminology, they would all become the same kind.  Maude, in particular, would give you lots and lots of pre-regularity warnings when you collapse diffent syntactic categories.

I actually think that the parser should do _nothing_ about brackets and it is a mistake that it does.  Brackets should just be macros `rule (I:Int) => I  [macro]`.

However, I do not insist on that now, and I suggest that we all refrain from trying to come up with _new_ things before Jan 18.  We do not know how these new things interact with the rest of the system and conventions, and we may end up wasting a day trying something that does no work.  And one day means 3% of the time we have.  We should just fix/patch bugs, so we can execute all the tutorial, the C semantics, and make sure we transfer all the meaningful error messages that we had in 3.6.  In other words, that we have everything that we need to not have to look back at 3.6 once we make the transition to 4.0.

We will come up with perfect solutions to everything afterwards.

**Comment by dwightguth** [comment] 2015-12-23 17:18
I am pretty sure the root cause of this issue is that if multiple bracket productions can be chosen for any particular location, they are not chosen in any particular order. I have talked about having some kind of unparser-prefer and unparser-avoid attributes to allow us to have a bit more control over the order in which productions are chosen by the unparser but we have not implemented anything like this yet. You are welcome to do this yourself if you would like to see this fixed though.

**Comment by grosu** [comment] 2015-12-30 13:58
@radumereuta , @cos: guys, we need to switch back to parentheses (instead of backticks) asap.  Can you just make the change and we'll deal with bugs afterwards?  We cannot do the tutorial otherwise, so this is on the critical path.

**Comment by radumereuta** [comment] 2015-12-30 21:23
Adding parenthesis back as brackets is easy. Just go to `kast.k`, in module `KSEQ` and add:
`syntax KBott     ::= "(" K ")"    [bracket]` next to the one with backticks. I haven't tried it, and I don't know what kind of error may appear because of this, so please give it a try.
I'm away, with dodgy internet. I can try and do it myself on Monday.

**Comment by radumereuta** [comment] 2015-12-30 21:25
And for now, add only the one for `K`, since it should be enough for all other sorts.
Yes, we should have it for other sorts too, but there might be problems with overloading (I haven't forgot about it).

**Comment by cos** [comment] 2016-10-31 20:17
@radumereuta, can this be closed?

**Comment by radumereuta** [comment] 2016-11-02 12:32
I haven't seen similar problems since then. I believe it is safe to close it.

**Closed as completed by radumereuta** 2016-11-02 12:32 UTC
Labels: bug
