### ISSUE TITLE
Finalize streams I/O

### ISSUE THREAD

**Issue by dwightguth** [kframework/k-legacy#1668] opened 2015-08-31 15:13 UTC
There is still some issue of the compiler pass for streams IO which adds #parseInput to the stdin cell.

**Comment by bmmoore** [comment] 2015-09-01 17:23
We are also planning to change the syntax back to use an attribute, rather than a reserved cell name.

**Comment by daejunpark** [comment] 2015-09-01 19:18
@dwightguth Do you agree with this change of syntax back to the original style? I just wanted to be confirmed before implementing it.

**Comment by bmmoore** [comment] 2015-09-01 19:33
Specifically, we discussed this in the K meeting on Monday, and couldn't come up with any compelling arguments for breaking backwards compatibility.

**Comment by dwightguth** [comment] 2015-09-01 19:50
I mean, I did it the way that I chose to in order to make it simpler to implement because it means that you don't have to keep track of which cells have streams in them and then run a compiler pass to generate the stream rules from the IO module. I don't particularly have any objection to reimplementing all that junk because it doesn't really affect me one way or the other, but this solution is a lot cleaner and requires much more minimal intervention from the compiler.

**Comment by grosu** [comment] 2015-09-02 19:27
Why is the current solution "a lot cleaner"?  We want to be able to stream data to cells in K in the long term.  Your solution, @dwightguth, does not get us any closer to that.  Unless you or anybody else comes up with a better design, we stick to what we have now.

As a general rule of thumb, from here on I want to be part of the loop when changes are being made to the design of K that require changing the tutorial and the movies.

**Comment by grosu** [comment] 2015-09-04 13:02
@daejunpark , can you please give us an ETA on this?  We do not want to modify the definitions to work with `<stdin/>`, etc., only to have to change them back in a few hours or days.  If the problem is difficult, please let us know.  But the point is that, for now, you should not do anything conceptually new or different from what we had.

**Comment by daejunpark** [comment] 2015-09-04 15:38
I'm hoping to finish today or early next week. I'll get the temporary modification back to the original once I fix this.

**Comment by grosu** [comment] 2015-09-14 17:08
@daejunpark so it looks like we are done with this, right?  Is there a way to mark this task as done in the milestone, without removing it?

**Comment by daejunpark** [comment] 2015-09-14 17:22
Yes, we are done with this. I have no idea how to mark it in such a way.

**Comment by bmmoore** [comment] 2015-09-14 19:40
If we just close this issue, it will show up under the "Closed" tab on the milestone's page.

**Comment by daejunpark** [comment] 2015-09-15 05:13
Closed via #1716

**Closed as completed by daejunpark** 2015-09-15 05:13 UTC
