### ISSUE TITLE
. instead of .List error message confusing

### ISSUE THREAD

**Issue by traiansf** [kframework/k-legacy#548] opened 2014-06-04 08:16 UTC
I simply used . in a rule where .List was expected:

  rule <k> letrec X:Id = E1:Exp in E2:Exp => E2[letrec X = E1 in E1 / X] ...</k>
       <trace>... . => ListItem(letrec X:Id = E1:Exp in E2:Exp) </trace>

However, It took me about 5 minutes to realize what the following error means:

  [Error] Critical: unexpected left-hand side data structure format; expected
  elements and at most one variable
  '_List_(GeneratedFreshVar368:List ,, .K)
        File: ...

Maybe we should consider at least giving an advice together with this error.

**Comment by dwightguth** [comment] 2015-04-27 17:49
Duplicate of #373

**Closed as completed by dwightguth** 2015-04-27 17:49 UTC
